[network]
name = "devnet"

[accounts.deployer]
mnemonic = "lesson couple tackle family occur miracle catch person drive surround choice rubber spice friend double coast dream what ethics leader reward party ketchup seek"
balance = 1_000_000_000_000

[accounts.wallet_1]
mnemonic = "beef alert ridge vacuum quote blind crisp interest genuine romance floor sort trap morning annual roof brick umbrella bid party screen adult figure sniff"
balance = 100_000_000_000

[accounts.wallet_2]
mnemonic = "nerve skull cigar convince pole start ridge have humor kit exhibit ring please captain lunar draft civil swim design glare concert fiber comfort elephant"
balance = 100_000_000_000

[accounts.wallet_3]
mnemonic = "jungle boat rebuild require grunt vibrant girl rather egg color cruise logic matter trouble beef caution job purity already dilemma reopen analyst develop search"
balance = 100_000_000_000

[devnet]
enable_subnet_node = false
bitcoin_controller_block_time = 30_000
working_dir = "/tmp/paybridge-devnet"
orchestrator_port = 20445
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
bitcoin_node_username = "devnet"
bitcoin_node_password = "devnet"
bitcoin_node_image_url = "quay.io/hirosystems/bitcoind:devnet-v3"
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_node_image_url = "quay.io/hirosystems/stacks-node:devnet-v3"
stacks_api_port = 3999
stacks_api_events_port = 3700
stacks_api_image_url = "hirosystems/stacks-blockchain-api:latest"
stacks_explorer_port = 8000
stacks_explorer_image_url = "hirosystems/explorer:latest"
bitcoin_explorer_port = 8001